name: Publish ROMs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-roms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Download Git LFS objects
        run: |
          git lfs install
          git lfs pull

      - name: Upload ROMs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.sha }}
        shell: bash
        run: bash ./.github/scripts/publish-roms.sh

      - name: Finish
        run: echo "Proceso terminado correctamente."
